#pragma once

#include "NativeGameplayTags.h"

namespace ASGameplayTags
{
	// Input Tags
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash);

	// Player Tags
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Dash);

	// Player Status
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Dash);

	// Player Anim Notify
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	// Enemy Tags
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_HitPause);

	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);

	// Enemy Anim Notify
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_HitPause);

	// Shared Tags
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);

	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_WeaponAttackPower);
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamageFactor);
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_RestoreValue);
	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseRestoreFactor);

	ACTIONSHOOTERGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Death);
}
